language: python
python:
  - "3.6"      # current default Python on Travis CI
# command to install dependencies and coverage
install:
 - pip install -r requirements.txt
 - pip install coverage
# command to run tests
script:
 - invoke testApi