version: '3'

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    networks:
      - local
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5

  mongo-seed:
    build: ./mongo
    networks:
      - local
    links:
      - mongodb

  v1:
    build: './V1'
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - mongodb
    environment:
      - PORT=5000
    networks:
      - local

  v2:
    build: './V2'
    ports:
      - "5050:5050"
    restart: always
    depends_on:
      - mongodb
    environment:
      - PORT=5050
    networks:
      - local

networks:
  local:
    driver: bridge