version: '3'

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    networks:
      - local
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5

  mongo-seed:
    build: ./mongo
    networks:
      - local
    links:
      - mongodb

  v1:
    build: './V1'
    restart: always
    depends_on:
      - mongodb
    environment:
      - PORT=${V1_DOMAIN}
    networks:
      - local
    links:
      - mongodb

  v2:
    build: './V2'
    restart: always
    depends_on:
      - mongodb
    environment:
      - PORT=${V2_DOMAIN}
    networks:
      - local
    links:
      - mongodb

networks:
  local:
    driver: bridge